### ISSUE TITLE
Proxy fails to start in case of file cache

### ISSUE THREAD

**Issue by okbp** [dbcls/sparql-proxy#11]
In latest container, proxy(web server) fails to start .

Here is my docker-compose.yml
```
version: '3'
services:
  proxy:
    image: dbcls/sparql-proxy:latest
    container_name: sparql_proxy
    user: ${UID:-0}:${GID:-0}
    ports:
      - 3010:3000
    volumes:
      - ${PWD}/data/sparql-proxy:/data/sparql-proxy
      - ${PWD}/logs/sparql-proxy:/var/log/sparql-proxy
    environment:
      CACHE_STORE_PATH: /data/sparql-proxy
      CACHE_STORE: "file"
      PASSTHROUGH: "true"
      QUERY_LOG_PATH: /var/log/sparql-proxy/sparql-proxy.log
      SPARQL_BACKEND: http://localhost:8890/sparql
```

```
$ mkdir -p data/sparql-proxy
$ mkdir -p logs/sparql-proxy
$ docker-compose up -d
Creating sparql_proxy ... done

$ docker logs sparql_proxy
> sparql-proxy@0.0.0 start /app
> NODE_PATH=src node --experimental-modules src/server.js

(node:19) ExperimentalWarning: The ESM module loader is experimental.
Passthrough mode is enabled. Query filtering and splitting are disabled.
cache store: file (compressor: raw)
(node:19) UnhandledPromiseRejectionWarning: Error: Cannot find module /app/src/cache/base imported from /app/src/cache/file.js
    at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:82:13)
    at Loader.resolve (internal/modules/esm/loader.js:73:33)
    at Loader.getModuleJob (internal/modules/esm/loader.js:147:40)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:41:40)
    at link (internal/modules/esm/module_job.js:40:36)
(node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:19) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

When 'CACHE_STORE_PATH' & 'CACHE_STORE' environments are commented out, it works.
And previous version(Created: 2019-03-13T07:20:10) was not getting this error.

**Comment by ursm** [comment]
Thank you for the report. I have fixed this issue in the master branch, can you confirm it?

**Comment by okbp** [comment]
Thanks for your prompt response !

Proxy server started up normally, but when execute query I got error message below and the cache file is not output.
```
ERROR: in cache put: TypeError: fs.ensureDir is not a function
    at default.put (file:///app/src/cache/file.js:37:14)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async default.tryCache (file:///app/src/job.js:247:7)
    at async Item.run (file:///app/src/queue.js:41:20)
    at async default.tryDequeue (file:///app/src/queue.js:167:7)
```
changed environment
```
SPARQL_BACKEND=https://dbpedia.org/sparql
```
test query
```
SELECT * { <http://dbpedia.org/resource/Tokyo> ?p ?o } LIMIT 10
```

**Comment by ursm** [comment]
That's exactly what you say. Can you try it again?

**Comment by okbp** [comment]
Thank you. I confirmed that this issue was fixed!
But the container image that can be downloaded from [DockerHub](https://hub.docker.com/r/dbcls/sparql-proxy) does not reflect the correction(Build hash is correct. I don't know why. hmm....).
Therefore, I confirmed it with the image I built from the GitHub source.

```
$ git clone https://github.com/dbcls/sparql-proxy.git
$ cd sparql-proxy
$ docker build -t dbcls/sparql-proxy:latest .
```

And I recommend the Docker tagging to provide a stable version.

**Comment by ursm** [comment]
Sorry for the inconvenience. Docker Hub image was not updated because Dockerfile was incorrect. I intend to fix it with [this commit](https://github.com/dbcls/sparql-proxy/commit/71bf21444f5bd7b186c96fd8b7a3f56a055fd77a).

I think it's reasonable to provide a stable version, but we need more thought.

**Comment by okbp** [comment]
I confirmed that latest image on DockerHub works fine!
Thank you!
