### ISSUE TITLE
clear cache fails with the 'file' mode

### ISSUE THREAD

**Issue by okbp** [dbcls/sparql-proxy#24]
Pressing the 'Purge cache' button on the admin page did not clear the cache and the following error was displayed in the running.log
```
(node:29439) UnhandledPromiseRejectionWarning: TypeError: fs.remove is not a function
    at default.purge (file:///data/genome/sparql-proxy-app/src/cache/file.mjs:42:14)
    at Socket.<anonymous> (file:///data/genome/sparql-proxy-app/src/server.mjs:263:19)
    at Socket.emit (events.js:315:20)
    at /data/genome/sparql-proxy-app/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
(node:29439) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
```
Then, I've recreate the 'cache' directory in the deployment directory.

**Comment by ursm** [comment]
I'm sorry, this is obviously my mistake. I've fixed it, could you confirm that the problem has been resolved?

**Comment by okbp** [comment]
Thank you! It works
