### ISSUE TITLE
Service descriptionを取得しようとすると落ちる

### ISSUE THREAD

**Issue by okbp** [dbcls/sparql-proxy#53]
20230210版のソースコードをビルドして使用しています。
エンドポイントに引数なしのGETリクエスト(Service descriptionを取る際のリクエスト)を送るとProxyが落ちます。
```
$ curl -L -H "Accept: text/turtle, text/n3, application/n-triples, application/n-quads, application/rdf+xml, application/rdf+json, application/ld+json, application/trig, application/trix" "https://xxxx.org/xxxx/sparql"
```
落ちた時のログです。
```
file:///app/src/server.mjs:119
      if (fs.pathExistsSync(`${__dirname}/../files/description.${ext}`)) {
             ^

TypeError: fs.pathExistsSync is not a function
    at returnServiceDescription (file:///app/src/server.mjs:119:14)
    at file:///app/src/server.mjs:102:13
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
    at multerMiddleware (/app/node_modules/multer/lib/make-middleware.js:18:41)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
    at cors (/app/node_modules/cors/lib/index.js:188:7)
    at /app/node_modules/cors/lib/index.js:224:17
    at originCallback (/app/node_modules/cors/lib/index.js:214:15)
```
再現するかご確認頂きたいです。

**Comment by darashi** [comment]
ありがとうございます。たしかに、再現できました。

応急的には

```diff
diff --git a/src/server.mjs b/src/server.mjs
index c7f30ab..e6fe80a 100644
--- a/src/server.mjs
+++ b/src/server.mjs
@@ -116,7 +116,7 @@ const fs = _fs.promises;
     if (matchedType) {
       const ext = typeToExt[matchedType];
 
-      if (fs.pathExistsSync(`${__dirname}/../files/description.${ext}`)) {
+      if (_fs.existsSync(`${__dirname}/../files/description.${ext}`)) {
         res
           .type(matchedType)
           .sendFile(`files/description.${ext}`, { root: `${__dirname}/..` });

```

とすると問題なく動くかと思うのですが、いかがでしょうか。

**Comment by okbp** [comment]
ありがとうございます。運用環境で適用して問題が発生しなくなる事を確認しました。
mainに取り入れて頂ければ有り難いです。

**Comment by darashi** [comment]
main に入れました！
